class Symptoms {
  static const List<String> commonSymptoms = [
    'Headache',
    'Fever',
    'Cough',
    'Cold / Runny Nose',
    'Sore Throat',
    'Stomach Ache',
    'Nausea / Vomiting',
    'Dizziness',
    'Body Pain',
    'Fatigue / Weakness',
    'Allergic Reaction',
    'Skin Rash',
    'Eye Irritation',
    'Difficulty Breathing',
    'Chest Pain',
    'Diarrhea',
    'Toothache',
    'Injury / Wound',
    'Sprain / Fracture',
    'Fainting',
    'Anxiety / Panic Attack',
    'Other',
  ];
}
