const List<String> kSymptomsList = [
  'Headache',
  'Abdominal Pain',
  'General Pain',
  'NFW/Dizzy',
  'Wound',
  'Menstrual Pain',
  'Fever',
  'Asthma',
  'LBM',
  'Toothache/Oral Pain',
  'Nasal',
  'Cough',
  'Cold',
  'Vomit',
  'Sore Throat',
  'Sprain',
  'Due Meds Given',
  'Burn',
  'Eczema',
  'Sunburn',
  'Hypogastric Pain',
  'Nose Bleed',
  'Allergy',
  'Callus',
  'Rashes',
  'Acidic',
  'Panic Attacks',
  'Deltoid',
];
