const List<String> kSuppliesList = [
  'Bandage',
  'Cotton Balls',
  'Alcohol',
  'Betadine',
  'Gauze',
  'Medical Tape',
  'Band-Aid',
  'Thermometer Cover',
  'Disposable Gloves',
  'Face Mask',
  'Ice Pack',
  'Hot Compress',
  'Tongue Depressor',
  'Syringe',
  'Saline Solution',
  'Hydrogen Peroxide',
  'Eye Drops',
  'Ear Drops',
  'Paracetamol',
  'Ibuprofen',
  'Mefenamic Acid',
  'Antacid',
  'ORS Sachet',
  'Antihistamine',
  'Ointment',
  'Nasal Spray',
  'Cough Syrup',
  'Vitamin C',
];
